### ISSUE TITLE
[Final Project Pitches]

### ISSUE THREAD

**Issue by johnnybenson** [IDMNYU/DM2193SP2015#14]
Post your idea with supporting text images links whatever you need. Let's come to class Tuesday ready to talk about it.

**Comment by Azerafa** [comment]
For my final project I want to do a choose your own adventure of sorts. One webpage will display to things side by side, for example two pictures, two colors, two videos, two audio clips, and you have to choose one. When you click it moves onto the next choice and this keeps happening until you reach the end "destination" (new page) which is a picture of a "welcome to" sign from somewhere in the country (example image attached), 
![welcome-to-florida](https://cloud.githubusercontent.com/assets/8633448/7080488/069752a8-df01-11e4-8702-51a62ed4fde2.jpg)

**Comment by sds558** [comment]
For my final project I want do this sort of personality quiz,  where based on the answers you choose for each question, the site calculates what food you'd probably be in real life. You'd probably have up to 4 choices for each question, and each question might take a whole page. Once you pick answer a question, you are redirected to another question on another page, until you are eventually redirected to the final page, which shows an image and/or video of your food and an explanation of why.

---

Example
![sandwich](https://cloud.githubusercontent.com/assets/10818859/7081155/ba504f2a-df0b-11e4-8a47-dc93603f98bf.jpg)

Explanation: 
Based on your choices, we've concluded that you're a pretty normal person.
You're normal. 
Sandwiches are normal
Therefore you are a sandwich
the end

**Comment by ziros94** [comment]
My idea is NYU Mad Libs. Users have to input words based on the part of
speech requested. Stories will use these inputted words and display them in
an NYU story. I'll be using javascript to make the pages fun and
interactive.

I'll also black out the story until users input all the words
​

On Thu, Apr 9, 2015 at 11:04 PM, sds558 notifications@github.com wrote:

> For my final project I want do this sort of personality quiz, where based
> on the answers you choose for each question, the site calculates what food
> you'd probably be in real life. You'd probably have up to 4 choices for
> each question, and each question might take a whole page. Once you pick
> answer a question, you are redirected to another question on another page,
> until you are eventually redirected to the final page, which shows an image
> 
> ## and/or video of your food and an explanation of why.
> 
> Example
> [image: sandwich]
> https://cloud.githubusercontent.com/assets/10818859/7081155/ba504f2a-df0b-11e4-8a47-dc93603f98bf.jpg
> 
> Explanation:
> Based on your choices, we've concluded that you're a pretty normal person.
> You're normal.
> Sandwiches are normal
> Therefore you are a sandwich
> the end
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IDMNYU/DM2193SP2015/issues/14#issuecomment-91413173.

## 

Sincerely,

Alvi Kabir

**Comment by imAlan** [comment]
My idea is a level base riddle game that teaches you web development concepts. Each level will have a riddle in the form of a picture or text and will involve some type of interaction with the web browser or website. Concepts include robot.txt, google devtools, url, javascript, browser size ...

**Comment by mcdeeda** [comment]
my idea is a where's waldo / scavenger hunt game through old websites. the sites would link between each other and as the user goes between links, a simple map of how the sites are connected is laid out. there are different things to find on each page ranging in difficulty and value; a low-value object might be a low-quality "under construction" gif, but a higher-value one might be some deprecated HTML element.

**Comment by Jun500** [comment]
I wanted to draw and basically make a comic for my Final Project. So my idea is to have an interactive comic. The comic won’t be straight linear, but instead there will be free will to choose what you do and what you will see. During certain parts of the comic there will be multiple choices which will lead down a different set of images. I kind of want to make it a blend of something reminiscence of a text adventure, but also make it about something relating to my life. The entire over arcing website will act as a story.

**Comment by gitHubCal** [comment]
My idea for the final is to create a Instagram-like page where I put photos and videos. However, the photos will be partially blocked and the videos won't play unless you solve some randomly-generated Javascript puzzles to unblock those pictures and videos.

**Comment by oskarnoam** [comment]
Mattress Plus.

This is the story of a mattress salesman. He owns a mattress store in Burbank  -  CA. Mattress Plus. He’s ordinary. You might have stood in line at a salad bar with him. You might have told him ‘have a nice day’ or laughed about something together. He’s average. You won’t remember his face tomorrow. John Doe.

Outside the operational hours of his store is where things take a turn. His wife has the greatest understanding of who he is. After years of this “trying to make it work”, she decides to expose him for the man no else gets to see. She hacks into his web site and changes every link on a his page. Thus, the narrative of his wrong doing begins.

Why a mattress store? Because it’s so mundane, it’s bland - it’s him. It’s also the first thing a couple buys when they move in together.  The ‘plus’ signifies (in a manner that’s not exactly subtle) that there’s more to the site than it seems at first glance.

Cardsorting

![tumblr_nmoef796az1usxhyso1_1280](https://cloud.githubusercontent.com/assets/10839062/7129481/df14c644-e22e-11e4-977d-af9a77ee0aa8.jpg)

Storyboard
![tumblr_nmoef796az1usxhyso2_1280](https://cloud.githubusercontent.com/assets/10839062/7129483/df15f280-e22e-11e4-9f59-b322a3a1fd64.jpg)
![tumblr_nmoef796az1usxhyso3_1280](https://cloud.githubusercontent.com/assets/10839062/7129482/df152f4e-e22e-11e4-8aba-0aa0f024ca82.jpg)

Mockup
![tumblr_nmjt1ntiwl1usxhyso1_1280](https://cloud.githubusercontent.com/assets/10839062/7129504/5ac24140-e22f-11e4-8ee9-61b0213f15ce.png)

**Comment by therealshah** [comment]
Hey. My final project is going to be sorta a comic story (spinoff of flash
and arrow possibly). At each scene, the user will be asked to make a
choice. Depending on the choice, the story will take a route. I was also
thinking of having mini interactions with the user ( shooting arrows/
dodging obstacles). This will also have an impact on the story.

Thanks
Shahzaib

**Comment by itsjohnward** [comment]
For my final project, I'm thinking of merging the "choose your own adventure" thing with the mind-mapping idea we talked about in class. So the website is like a journey through my mind-map. A mind-map obviously isn't necessarily linear, and there can be loops and dead-ends and choices involved. So, the way the content is displayed is most important here; it can't just be something you click through. I think there's a lot of room for javascript and statefulness to make the journey interesting and playful.

**Comment by hillarychin** [comment]
I was originally going to expand upon my Quotes webpage with visuals but I couldn't figure out a way to make it more interactive so my new idea is a decision-based narrative website. I'm really into interactive games like The Walking Dead, Beyond Two Souls, Life Is Strange, Heavy Rain, etc. that let the user shape a story based on their choices as the story progresses. I was thinking of taking one of those video games and adapting it into website form, in a much more narrowed, simplified, and condensed way. It would tell the story of a singular scene or episode and the user would be able to make decisions as they navigate further and further into the site/scene. There would also be parts where the user could click around a room or on a character to find out more. (I could also write my own story, but I don't know if I'm up for being that creative).

![finalproject](https://cloud.githubusercontent.com/assets/10766175/7149244/fd3f114c-e2d8-11e4-9eed-e984a6e266f9.png)

**Comment by hchoi12345** [comment]
My final project is going to be a website for people who wants to read the bible.
There are many categories involving prophets, historical writings, poetry, epistles, and other things that make up the bible. I am going to make this website so that the user can have a fun experience reading and learning about the bible.
I will include images, so the user interacts with the website.
